spring:
  application:
    name: test-practice
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: 'jdbc:h2:mem:testdb'
      # jdbc-url: 'jdbc:h2:tcp://localhost/~/testdb'
      username: sa
      password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

jwt:
  secret-key: "rYfed5F12iViHmbB7ZufrxIR6MNLG67+4+b6+DhqcRJuFVe7/KxhIb4necxKaCDN"
